import type { Metadata } from 'next';
import './globals.css';
import { Container } from '@/components/container';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ToastifyContainer } from '@/components/ToastifyContainer';
import React from 'react';

export const metadata: Metadata = {
  title: {
    default: 'Create Next App',
    template: '%s | The Blog',
  },
  description: 'Generated by create next app',
};
type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='en' className=''>
      <body>
        <Container>
          <Header />

          {children}

          <Footer></Footer>
        </Container>
        <ToastifyContainer />
      </body>
    </html>
  );
}
